"""empty message

Revision ID: 4511e248d7a2
Revises: ac44680d9dd2
Create Date: 2020-02-12 13:30:36.412245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4511e248d7a2'
down_revision = 'ac44680d9dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'pages')
    # ### end Alembic commands ###
